config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"


  resources :superpowers do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:create]
  end

  resources :bookings, only: [:index, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :superpower
  belongs_to :user

  validates :start_date, :end_date, presence: true
  validate :start_date_cannot_be_in_the_past
  validate :end_date_after_start_date

  def total_price
    return 0 if start_date.nil? || end_date.nil?

    days = (end_date - start_date).to_i + 1
    days * superpower.price
  end

  private

  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    end
  end

  def end_date_after_start_date
    if start_date.present? && end_date.present? && end_date < start_date
      errors.add(:end_date, "must be on or after the start date")
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :superpower
end

app/models/superpower.rb
class Superpower < ApplicationRecord
  belongs_to :user

  has_many :reviews, dependent: :destroy
  


  has_many :bookings, dependent: :destroy
  has_one_attached :image

  has_one_attached :photo

  validates :name, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  def after_sign_in_path_for(resource)
    superpowers_path
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @superpower = Superpower.find(params[:superpower_id])
    @booking.superpower = @superpower
    @booking.user = current_user

    if @booking.save

     redirect_to bookings_path, notice: "superpower sucessfully booked"


    else

      render "superpowers/show", status: :unprocessable_entity
    end
  end

  def index
    @bookings = Booking.where(user: current_user)
    @review = Review.new
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :comment)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @superpowers = Superpower.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @superpower = Superpower.find(params[:superpower_id])
    @review = Review.new(review_params)
    @review.superpower = @superpower
    @review.user = current_user
    if @review.save
      redirect_to superpower_path(@superpower)
    else
      @bookings = Booking.where(user: current_user)
      render 'bookings/index', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/superpowers_controller.rb
class SuperpowersController < ApplicationController
  def index
    @superpowers = Superpower.all
  end

  def show
    @superpower = Superpower.find(params[:id])
    @booking = Booking.new
  end

  def new
    @superpower = Superpower.new
  end

  def create
    @superpower = Superpower.new(superpower_params)
    @superpower.user = current_user

    if @superpower.save
      redirect_to superpowers_path, notice: 'Superpower was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @superpower = Superpower.find(params[:id])

    if @superpower.user == current_user
      @superpower.destroy
      redirect_to superpowers_path, notice: "Superpower deleted successfully."
    else
      redirect_to superpowers_path, alert: "You can only delete your own superpowers!"
    end
  end

  private

  def superpower_params
    params.require(:superpower).permit(:name, :description, :price, :strength, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<% if booking.errors.any? %>

  <div class="alert alert-danger">
    <h4><%= pluralize(booking.errors.count, "error") %> prohibited this superpower from being booked:</h4>
    <ul>
      <% booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/bookings/_form_frame.html.erb
<turbo-frame id="booking_form">
  <%= render "bookings/form", booking: booking, superpower: superpower %>
</turbo-frame>

app/views/bookings/index.html.erb
<h1>Your Bookings</h1>

<div class="booking_container">
  <% @bookings.each do |booking| %>
    <div class="mybooking_box">
      <div class="booking_image">
        <% if booking.superpower.photo.present? %>
          <%= cl_image_tag booking.superpower.photo.key, height: 300, width: 200, crop: :fill, alt: booking.superpower.name, class: "superpower-image" %>
        <% else %>
          <p>No image available</p>
        <% end %>
      </div>
      <div class="booking_info">
        <p class="booking_detail">Superpower: &nbsp;<%= booking.superpower.name %></p>
        <p class="booking_detail">Start Date: &nbsp;<%= booking.start_date %></p>
        <p class="booking_detail">End Date: &nbsp;<%= booking.end_date %></p>
        <p class="booking_detail">Comment: &nbsp;<%= booking.comment %></p>
        <p class="booking_detail">Total Price: &nbsp;£<%= booking.total_price %></p>

        <%= link_to "Delete Booking", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>

        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary mt-2" data-bs-toggle="modal" data-bs-target="#reviewModal-<%= booking.id %>">
          Leave a Review
        </button>
      </div>
    </div>

    <!-- Modal (unique ID per booking) -->
    <div class="modal fade" id="reviewModal-<%= booking.id %>" tabindex="-1" aria-labelledby="modalLabel-<%= booking.id %>" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="modalLabel-<%= booking.id %>">Leave a Review</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="review-form">
              <%= simple_form_for [booking.superpower, Review.new] do |f| %>
                <%= f.input :comment, label_html: { class: "d-none" }, placeholder: "Review here...", class: "review" %>
                <%= f.input :rating, collection: 0..5 %>
              <div class="text-end">
  <%= f.submit "Send", class: "btn btn-primary" %>
</div>
              <% end %>
            </div>
          </div>
          <div class="modal-footer">
            <%# <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> %>
          </div>
        </div>
      </div>
    </div>

  <% end %>
</div>

<div class="back-link mt-4">
  <%= link_to "Back", superpowers_path, class: "btn btn-primary" %>
</div>

app/views/bookings/redirect.turbo_stream.erb
<turbo-stream action="replace" target="booking_form">
  <template>
    <div data-controller="redirect" data-url="<%= bookings_path %>"></div>
  </template>
</turbo-stream>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Twenty One Days Later Airbnb" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload"%>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/navbar" %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bangers&display=swap" rel="stylesheet">
<body class ="lp">
<section class= "FV">
<div class="banner" style="background-image: linear-gradient(rgba(0, 0, 0, 0.3),rgba(0, 0, 0, 0.3)), url('<%= image_path("fv_superpower.png") %>')">
  <div>
  <div class="container">
    <%= link_to 'BOOK A SUPERPOWER!', superpowers_path, class: "btn-flat1" %>
  </div>
<%# </div> %>
</section>


<section class="features">
        <div class="container">
            <div class="feature-grid">
                <div class="feature-text left">
                    <h2>NEED A HERO?<br>BECOME ONE.<br>RENT A POWER.</h2>
                </div>
                <div class="feature-image right">
                <%= image_tag "feauture1.jpg", alt: "test" %>
                </div>
            </div>

            <div class="feature-grid reverse">
                <div class="feature-image left">
                  <%= image_tag "feauture2.jpg", alt: "test" %>
                </div>
                <div class="feature-text right">
                    <h2>YOU'VE GOT THE CHOICE.<br>WE'VE GOT THE POWER.<br>LET'S SAVE THE DAY.</h2>
                </div>
            </div>
        </div>
    </section>


 <section class="reviews">
        <div class="container">
            <div class="reviews-grid">
                <div class="reviews_container">
                    <p>"My kids LOVED it.<br>Next time: invisibility!"<br>— Sarah, Mom of Two</p>
                </div>
                <div class="reviews_container">
                   <p>"Best birthday ever.<br>He flew for 10 minutes!"<br>— Mike, Proud Dad</p>
                </div>
                <div class="reviews_container">
                    <p>"Never seen her so confident.<br>Telekinesis = total win."<br>— Lena, Aunt Extraordinaire</p>
                </div>
            </div>
        </div>
    </section>

  <section class="powers">
  <div class="container">
    <h2 class="section-title">SUPER POWERS</h2>
    <div class="powers-grid">
      <% @superpowers.each do |superpower| %>
        <div class="power-card">
          <% if superpower.photo.present? %>
            <%= cl_image_tag superpower.photo.key, height: 200, width: 180, crop: :fit, alt: superpower.name, class: "superpower-image" %>
          <% else %>
            <p>No image available</p>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</section>


    </body>

app/views/shared/_footer.html.erb
<footer>
        <div class="container">
            <div class="footer-nav">
                <ul>
                    <li> <%= link_to "Home", root_path %></li>
                    <li> <%= link_to "SuperPowers", superpowers_path%></li>
                    <li>  <%= link_to "Sign up", new_user_session_path %></li>
                </ul>
            </div>
            <div class="social-icons">
                <a href="#"><i class="fab fa-youtube"></i></a>
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
            </div>
        </div>
        <div class="copyright">
            <p class="copyrighttext">&copy; 2025 Rent a Super Power. Power to the People.</p>
        </div>
    </footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", alt: "Logo", class: "logo-img" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "SuperPowers", superpowers_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My booking", bookings_path, class: "nav-link" %>
          </li>
            <li class="nav-item">
            <%= link_to "Add superpower",  new_superpower_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "user_icon.png", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My booking",  bookings_path, class: "dropdown-item" %>
              <%= link_to "Add superpower", new_superpower_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/superpowers/_superpower_form.html.erb
<div class='superpower-form-container'>
  <%= simple_form_for (@superpower) do |f| %>
    <%= f.input :name, label: 'Superpower Name' %>
    <%= f.input :description, label: 'Description' %>
    <%= f.input :price, label: 'Price' %>
    <%= f.input :strength, label: 'Strength Level' %>
    <%= f.input :photo, as: :file, label: "Upload Image", class: "superpower-image" %>
    <%= f.button :submit, class: 'glowing-btn' %>
  <% end %>
</div>

app/views/superpowers/index.html.erb
<div class="cards-home">
  <h1>SuperPowers!</h1>
  <h2>List of superpowers</h2>

  <div class="cards">
    <% @superpowers.each do |superpower| %>
      <div class="card">

        <% if superpower.photo.present? %>
          <%= link_to superpower_path(superpower) do %>
            <%= cl_image_tag superpower.photo.key, height: 300, width: 200, crop: :fill, alt: superpower.name, class: "superpower-image" %>
          <% end %>
          <% end %>




        <% if superpower.user == current_user %>
          <%= link_to "Delete", superpower_path(superpower),
              data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
              class: "btn btn-danger" %>
        <% end %>

      </div>
    <% end %>
  </div>

  <hr>
  <%= link_to "Add a New Superpower", new_superpower_path, class: "glowing-btn" %>
</div>

app/views/superpowers/new.html.erb
<div class="booking-container">
 <h1>Add a new superpower</h1>
 <%= render 'superpower_form', superpower: @superpower  %>
 <hr>
</div>

app/views/superpowers/show.html.erb
<h1>Book this Superpower</h1>
<div class="two-column-layout">
  <div class="left-container" style="color: black !important;">
    <!-- <h1>Book this Superpower</h1>
      <div class='superpower-form-container'>-->

        <h3><%= @superpower.name %></h3>
    <br>
    <p><strong>Description</strong>
      <br>
      <em><%= @superpower.description.truncate(100) %></em>
    </p>
    <br>
    <p><strong>Price - </strong> <%= @superpower.price.round %></p>
    <br>
    <p><strong>Strength - </strong> <%= @superpower.strength %></p>

  <ul>
  <% @superpower.reviews.each do |review| %>
    <li>
      <button type="button" class="review-btn">
        <%= review.comment %> <%= '⭐️' * review.rating %>
      </button>
    </li>
  <% end %>
</ul>
</div>

<div class="right-container">




<%= simple_form_for [@superpower, @booking] do |f| %>
  <%= f.input :start_date, as: :string, input_html: { type: 'date' } %>
  <%= f.input :end_date, as: :string, input_html: { type: 'date' } %>
  <%= f.input :comment, as: :text %>
  <p><strong>Total Price:</strong> <span id="total-price">0</span></p>
  <%= f.submit "Book Superpower", class: "btn btn-primary" %>
<% end %>


  </div>

</div>




<script>
  document.addEventListener("turbo:load", function () {
    const startDateInput = document.querySelector("#booking_start_date");
    const endDateInput = document.querySelector("#booking_end_date");
    const totalPriceElement = document.getElementById("total-price");
    const pricePerDay = <%= @superpower.price.to_i %>;

    function updateTotalPrice() {
      const startDate = new Date(startDateInput.value);
      const endDate = new Date(endDateInput.value);

      if (!isNaN(startDate) && !isNaN(endDate)) {
        const timeDiff = endDate - startDate;
        const days = Math.floor(timeDiff / (1000 * 60 * 60 * 24)) + 1;
        if (days > 0) {
          const total = days * pricePerDay;
          totalPriceElement.innerText = total;
        } else {
          totalPriceElement.innerText = 0;
        }
      }
    }

    startDateInput.addEventListener("change", updateTotalPrice);
    endDateInput.addEventListener("change", updateTotalPrice);
  });
</script>